// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <header
//       style={{
//         background:'lightblue',
//         padding: '1rem',
//       }}>
//         <p>header</p>
//       </header>
//       <body>{children}</body>
//       <footer style={{
//         background:'blue',
//         padding:'1rem'
//       }}>
//         <p>footer</p>
//       </footer>
//     </html>
//   )
// }
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <header
          style={{
            background: 'lightblue',
            padding: '1rem',
          }}
        >
          <p>header</p>
        </header>
        {children}
        <footer
          style={{
            background: 'blue',
            padding: '1rem',
          }}
        >
          <p>footer</p>
        </footer>
      </body>
    </html>
  )
}
